
create database testio;

use testio;

CREATE TABLE users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL,
password VARCHAR(255) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (email)
);

CREATE TABLE issues (
id INT(100) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
status int(1) NOT NULL,
author VARCHAR(255) NOT NULL,
labels VARCHAR(255) NOT NULL,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
id INT(100) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
issue VARCHAR(100) NOT NULL,
parent int(100) NULL,
author VARCHAR(255) NOT NULL,
avatr VARCHAR(255) NOT NULL,
text text NOT NULL,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);